language: python
sudo: required
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
addons:
  apt:
    packages:
      - libgnutls-dev
virtualenv:
  system_site_packages: false

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - flake8
  - pytest